version: '3.9'

services:
  client:
    build:
      context: client
      target: production
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 3001:3001
    networks:
      - proxy

  server:
    build:
      context: api
      target: production
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - chatter-backend

  postgres:
    image: postgres:15.5-bullseye
    environment:
      - POSTGRES_USER="${POSTGRES_USER:?error}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?error}"
      - POSTGRES_DB=chatter
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatter-backend

volumes:
  pgdata:
networks:
  chatter-backend:
